"""User table

Revision ID: 2b6da0a87bde
Revises: 
Create Date: 2022-10-27 23:28:23.115888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6da0a87bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_hash', sa.String(length=50), nullable=False))
    op.drop_constraint('User_password_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['password_hash'])
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_password_key', 'User', ['password'])
    op.drop_column('User', 'password_hash')
    # ### end Alembic commands ###
