"""User tabel

Revision ID: 3264428a1e9c
Revises: b942f43d0967
Create Date: 2022-10-29 23:28:08.803453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3264428a1e9c'
down_revision = 'b942f43d0967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('User', 'password_hash')
    # ### end Alembic commands ###
