"""User table

Revision ID: b094a5fa40c8
Revises: 2b6da0a87bde
Create Date: 2022-10-27 23:53:36.191241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b094a5fa40c8'
down_revision = '2b6da0a87bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('User_password_hash_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_password_hash_key', 'User', ['password_hash'])
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
